src/objects/Fulfillment_Request__c/Fulfillment_Request__c.object-meta.xml
<CustomObject>
    <label>Fulfillment_Request</label>
    <nameField>
        <label>Fulfillment_Request__c  Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Fulfillment_Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Fulfillment_Request__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Order</label>
    <referenceTo>Order</referenceTo>
    <relationshipLabel>Fulfillment_Requests</relationshipLabel>
    <relationshipName>Fulfillment_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

src/objects/OrderFulfillmentRequestEvent__e/OrderFulfillmentRequestEvent__e.object-meta.xml
<CustomObject>
    <label>OrderFulfillmentRequestEvent</label>
    <pluralLabel>OrdersFulfillmentRequestEvent</pluralLabel>
</CustomObject>

src/objects/OrderFulfillmentRequestEvent__e/fields/FulfillmentRequestId__c.field-meta.xml
<CustomField>
    <fullName>FulfillmentRequestId__c</fullName>
    <label>FulfillmentRequestId</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

src/objects/OrderFulfillmentRequestEvent__e/fields/OrderId__c.field-meta.xml
<CustomField>
    <fullName>OrderId__c</fullName>
    <label>OrderId</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

src/classes/OrderReadyQueueable.cls
public class OrderReadyQueueable implements Queueable {
    private Id orderId;

    public OrderReadyQueueable(Id orderId) {
        this.orderId = orderId;
    }

    public void execute(QueueableContext context) {
        Order orderRec = [SELECT Id, Status,Name FROM Order WHERE Id = :orderId LIMIT 1];
        orderRec.Status = 'Ready for Fulfillment';
        update orderRec;

        Fulfillment_Request__c fulfillmentReq = new Fulfillment_Request__c(Order__c = orderId);
        insert fulfillmentReq;

        /*OrderFulfillmentRequestEvent__e event = new OrderFulfillmentRequestEvent__e(
            FulfillmentRequestId__c = fulfillmentReq.Id,
            OrderId__c = orderId
        );
        EventBus.publish(event);*/
    }
}