force-app/main/default/objects/Generic_Case_KPI__c/Generic_Case_KPI__c.object-meta.xml
<CustomObject>
    <label>Generic Case KPI</label>
    <nameField>
        <displayFormat>GKPI-{0000000000}</displayFormat>
        <label>Generic Case KPI Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Generic Case KPI</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Generic_Case_KPI__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Generic Case KPI</relationshipLabel>
    <relationshipName>Generic_Case_KPI</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Generic_Case_KPI__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Generic Case KPI</relationshipLabel>
    <relationshipName>Generic_Case_KPI</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Generic_Case_KPI__c/fields/SerialNumber__c.field-meta.xml
<CustomField>
    <fullName>SerialNumber__c</fullName>
    <label>SerialNumber</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Generic_Case_KPI__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Sample Device Handover</fullName>
            </value>
            <value>
                <fullName>Loan Device Handover</fullName>
            </value>
            <value>
                <fullName>Trial Device Handover</fullName>
            </value>
            <value>
                <fullName>Trial Device Return</fullName>
            </value>
            <value>
                <fullName>Loan Device Return</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/GnrcVstKeyPerformanceInd/fields/SerialNumber__c.field-meta.xml
<CustomField>
    <fullName>SerialNumber__c</fullName>
    <label>Serial Number</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/HandoverSerilizedProductCase.cls
public with sharing class HandoverSerilizedProductCase {
    
    @InvocableMethod(label='Handover serilized Product from Case' description='Create case Mapping with serialized products' category='GnrcVstKeyPerformanceInd')
    public static List<Response> getRecordsForKPIs(List<Requests> rqstInputs){
        try{
            //input varaibles from flow
            string productId = rqstInputs[0]?.productId;
            string caseId = rqstInputs[0]?.caseId;
            String type = rqstInputs[0]?.type;
            List<string> serialnumbersList = rqstInputs[0]?.serialnumbersList;
            List<Generic_Case_KPI__c> gencaseKpisList = new List<Generic_Case_KPI__c>();
            
            for(String srno: serialnumbersList){
                if(srno != null && srno != ''){
                    Generic_Case_KPI__c genCasKPI = new Generic_Case_KPI__c();
                    genCasKPI.SerialNumber__c = srno;
                    genCasKPI.Case__c=caseId;
                    genCasKPI.Product__c=productId;
                    genCasKPI.Type__c = type;
                    gencaseKpisList.add(genCasKPI);  
                }
                
                System.debug('-->srNo'+srno);
            }
            System.debug('-->'+gencaseKpisList);
            //send updated list to flow and flow will update the records
            List<Response> results = new List<Response>();
            Response objResponse = new Response();
            objResponse.genericCaseKpis = gencaseKpisList;  
            results.add(objResponse);
            
            return results;
        }catch(Exception e){
            throw new ReturnProductKPIDetailsException(e.getMessage());
        }
    }
    public class ReturnProductKPIDetailsException Extends Exception{}
    
    public class Requests {
        @InvocableVariable
        public List<String> serialnumbersList;
        @InvocableVariable
        public String caseId;
        @InvocableVariable
        public String productId;
        @InvocableVariable
        public String type;
        
    }
    
    Public Class Response{
        @InvocableVariable
        public List<Generic_Case_KPI__c > genericCaseKpis;  
    }
    
}